spring.application.name=DGA_DB_MANAGER
server.port=3000

spring.datasource.url:jdbc:sqlserver://localhost:1433;databaseName=DGA_DB_MANAGER;encrypt=false
spring.datasource.username:sa
spring.datasource.password:Elo136104!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

api.security.token.secret=dga-bd-security-key