export const ptBr = {

    'en': {
        'addFilter': '+ Adicionar filtro',
        'and': 'E',
        'apply': 'Aplicar',
        'booleanFirst': '☐',
        'booleanLast': '☑',
        'cancel': 'Cancelar',
        'CONTAINS': 'contém',
        'CONTAINS_CASE_SENSITIVE': 'contém (case sensitive)',
        'dateFirst': '1',
        'dateLast': '9',
        'DOES_NOT_CONTAIN': 'não contém',
        'DOES_NOT_CONTAIN_CASE_SENSITIVE': 'não contém (case sensitive)',
        'EMPTY': 'vazio',
        'ENDS_WITH': 'termina com',
        'ENDS_WITH_CASE_SENSITIVE': 'termina com (case sensitive)',
        'EQUAL': 'igual',
        'EQUAL_CASE_SENSITIVE': 'igual (case sensitive)',
        'filter': 'Filtro',
        'filteredByMultiple': '{{n}} filtros',
        'filteredByOne': '1 filtro',
        'filterValuePlaceholder': 'Valor',
        'find': 'Encontrar um campo',
        'findInView': 'Encontrar na visualização',
        'firstBy': 'Ordenar por',
        'found': '{{nth}} de {{n}}',
        'from': 'de',
        'GREATER_THAN': 'maior que',
        'GREATER_THAN_OR_EQUAL': 'maior ou igual',
        'LESS_THAN': 'menor que',
        'LESS_THAN_OR_EQUAL': 'menor ou igual',
        'noFilters': 'Nenhum filtro aplicado',
        'noResults': 'Sem resultados',
        'noSorting': 'Nenhuma ordenação aplicada',
        'NOT_EMPTY': 'não vazio',
        'NOT_EQUAL': 'diferente de',
        'NOT_NULL': 'não nulo',
        'NULL': 'nulo',
        'numberFirst': '1',
        'numberLast': '9',
        'ok': 'OK',
        'or': 'Ou',
        'pickAnother': 'Escolha outro campo para ordenar',
        'sort': 'Ordenar',
        'sortedByMultiple': 'Ordenado por {{n}} campos',
        'sortedByOne': 'Ordenado por 1 campo',
        'STARTS_WITH': 'começa com',
        'STARTS_WITH_CASE_SENSITIVE': 'começa com (case sensitive)',
        'stringFirst': 'A',
        'stringLast': 'Z',
        'thenBy': 'depois por',
        'where': 'Onde',
        'actionsIcon': 'Ícone de ações',
        'addNewStatus': 'Novo status',
        'addNewTask': 'Nova tarefa',
        'addSubtask': 'Nova subtarefa',
        'assignedTo': 'Atribuído a',
        'checklist': 'Checklist',
        'color': 'Cor',
        'commentsIcon': 'Ícone de comentários',
        'copy': 'Duplicar',
        'customize': 'Personalizar tarefas',
        'dueDate': 'Data de vencimento',
        'edit': 'Editar',
        'editTask': 'Editar tarefa "{{taskId}}"',
        'high': 'Alta',
        'low': 'Baixa',
        'newComment': 'Novo comentário',
        'newSubtask': 'Nova subtarefa',
        'normal': 'Normal',
        'priority': 'Prioridade',
        'priorityIcon': 'Ícone de prioridade',
        'progress': 'Progresso',
        'promptComment': 'Tem certeza de que deseja remover este comentário?',
        'promptTask': 'Tem certeza de que deseja remover a tarefa "{{taskText}}"?',
        'remove': 'Remover',
        'removeSubtask': 'Remover subtarefa',
        'send': 'Enviar',
        'startDate': 'Data de início',
        'status': 'Status',
        'swimlane': 'Faixa de natação',
        'tags': 'Tags',
        'text': 'Texto',
        'userId': 'ID do usuário',
        'userIcon': 'Ícone do usuário',
        'detailsTab' : 'Detalhes',
        'subtasksTab' : 'Sub-tarefa',
        'removeColumn': 'Remover coluna',
        'hideColumn' : 'Esconder coluna',
        'showAllColumns' : 'Mostrar todas as colunas',
        'tasksSummaryOne' : '1 tarefa',
        'tasksSummary' : '{{summary}} tarefas',
        'commentsTab'   : 'Comentários',
        'empty'         : 'vazio',
        'description'   : 'Descrição'
    },

};
